### ISSUE TITLE
Bug: matplotlib.pyplot error 

### ISSUE THREAD

**Issue by johannesschabbauer** [labscript-suite/lyse#101] opened 2022-11-21 12:34 UTC
## Description
Hi *labscript* Team!

For some analysis scripts to plot data, I get an error from pyplot. This happens only the first time running the script after launching Lyse, and only if matplotlib has to call figure(), subplots() or similar (just using  pyplot.plot does not cause the error for some reason).

I have matplotlib version 3.5.3 and lyse  3.1.0rc2.dev84+g1f0c876.

## Example

The error can be reproduced by running the following script on the first shot after launching Lyse:
```
import matplotlib.pyplot as plt

fig, ax = plt.subplots(2,1)

# further code for plotting...
```

This is the full error traceback that is printed:
```
File "/home/johannes/labscript-suite/lyse/lyse/analysis_subprocess.py", line 323, in do_analysis
    exec(code, self.routine_module.__dict__)

  File "/home/johannes/labscript-suite/userlib/analysislib/leolab/test.py", line 5, in <module>
    fig, ax = plt.subplots(2,1)

  File "/home/johannes/.conda/envs/labscript/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1453, in subplots
    fig = figure(**fig_kw)

  File "/home/johannes/labscript-suite/lyse/lyse/figure_manager.py", line 77, in __call__
    number, fig =  self.get_first_empty_figure(identifier, *args,**kwargs)

  File "/home/johannes/labscript-suite/lyse/lyse/figure_manager.py", line 33, in get_first_empty_figure
    fig = self._figure(i,*args,**kwargs)

  File "/home/johannes/.conda/envs/labscript/lib/python3.9/site-packages/matplotlib/pyplot.py", line 806, in figure
    manager = new_figure_manager(

  File "/home/johannes/.conda/envs/labscript/lib/python3.9/site-packages/matplotlib/pyplot.py", line 324, in new_figure_manager
    _warn_if_gui_out_of_main_thread()

  File "/home/johannes/.conda/envs/labscript/lib/python3.9/site-packages/matplotlib/pyplot.py", line 314, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod())

  File "/home/johannes/.conda/envs/labscript/lib/python3.9/site-packages/matplotlib/pyplot.py", line 217, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))

  File "/home/johannes/.conda/envs/labscript/lib/python3.9/site-packages/matplotlib/pyplot.py", line 301, in switch_backend
    globals()[func_name].__signature__ = inspect.signature(

AttributeError: 'method' object has no attribute '__signature__'
```

## Explanation and possible solution

The error above in the line `globals()[func_name].__signature__ = inspect.signature(` happens for `func_name="show"`, when matplotlib does something for registering the backend. This function in the globals was overwritten in [`figure_manager.py`](https://github.com/labscript-suite/lyse/blob/master/lyse/figure_manager.py#L143) from the default `show` function of pyplot. 

Now it turns out that here it makes a difference if `show` is defined as a function, as in pyplot, or as a method of the class FigureManger in Lyse, because for the method we cannot set the `__signature__` how to call is as attribute. 
A quite simple solution to resolve the error is to make sure `show` is not a class method but a function by changing the linked line in `figure_manager.py` to:

`matplotlib.pyplot.show = lambda: figuremanager.show`

Do you think that changing this line makes sense? Or should I create subplots differently in lyse?
I did not yet really understand why we need to overwrite some of the pyplot functions.

**Comment by dihm** [comment] 2023-03-10 21:29
Thanks for reporting it in such detail and providing an analysis!

I've actually just noticed this today in our experiments. I wonder what actually caused the change here, since this is definitely not how things behaved in the past. It's also interesting that is only happens on the first shot. Now that I think about it, I wonder if it happens if you manually close the figure window after the first shot as well? 

Anyway, this does seem pretty subtle. That said, the fix also seems trivial. I'd like to do a little more digging before just implementing the trivial fix.

**Comment by dihm** [comment] 2023-03-13 17:08
Did a little more looking in to this. Apparently this has been an issue since matplotlib v3.3.0 when they changed how the backends load (basically they convert the supplied module into a class which is then loaded). A little annoying since we are starting with a class, fudging it to a module, only to have it fudged back to a new class. Ugh...

Also, I confirmed that the error does not happen again if the plot is closed. It really is only an issue on the initial backend loading, and it appears to be ignored after a single failure a process restart.

Anyway, it does look like they are moving to a new method of backend loading, but it is based on something completely different. I think the fix you've proposed is appropriate for now. I'll go ahead and implement it.

**Closed** 2023-04-12 20:37 UTC
